import Head from "next/head";
import Image from "next/image";
import dynamic from "next/dynamic";
import { Inter } from "@next/font/google";
// import styles from "@/styles/Home.module.css";
import UserDashboardLayout from "@/components/layouts/UserDashboardLayout";
import UpdateUser from "@/components/page/dashboard/Profile/Update";
import NormalLayout from "@/components/layouts/NormalLayout";
import Section from "@/components/utils/Section";
import Container from "@/components/utils/Container";
import UserDashboardSidebar from "@/components/partials/dashboard/UserDashboardSidebar";
import MultiStepForm from "@/components/utils/MultiStepForm";
const inter = Inter({ subsets: ["latin"] });
import Form from "../../../components/page/dashboard/Properties/FormFields/index";
import { useEffect, useState } from "react";
import { structure } from "addPropertypageStructure";
export default function AddProperty(prop) {
  // const [astructure, setStructure] = useState({});

  // useEffect(() => {
  //   setStructure(JSON.parse(prop.structure));
  // }, []);
  return (
    <>
      <Head>
        <title>MyRAJ | Add Property</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={""}>
        <UserDashboardLayout>
          <Form structure={structure} />

          {/* <MultiStepForm /> */}
        </UserDashboardLayout>
      </main>
    </>
  );
}

// export async function getServerSideProps(context) {
//   structure.sections.forEach((section) => {
//     section.subSections.forEach(async (subSection) => {
//       if (subSection.dataUrl) {
//         let response = subSection?.dataUrl();

//         let data = response.data.data;
//         data = data.map((i) => {
//           return {
//             id: i.id,
//             label: i.name_en || i.name,
//             value: i.name_en || i.name,
//           };
//         });

//         switch (subSection.fieldType) {
//           case "btn_radio":
//             subSection.radios = data;
//             break;
//           case "select":
//             subSection.options = data;
//             break;
//           default:
//             break;
//         }
//       }
//     });
//     return {
//       props: {
//         structure: JSON.stringify(structure),
//       },
//     };
//     // console.log(structure.sections[1].subSections[0]);
//   });
// }
