import Head from "next/head";
import Image from "next/image";
import dynamic from "next/dynamic";
import { Inter } from "@next/font/google";
import UserDashboardLayout from "@/components/layouts/UserDashboardLayout";
import FavoritePropertiesContainer from "@/components/page/dashboard/Properties/Favorite";

const inter = Inter({ subsets: ["latin"] });

export default function AddProperty(prop) {
  return (
    <>
      <Head>
        <title>MyRAJ | My Properties</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={""}>
        <UserDashboardLayout>
          <FavoritePropertiesContainer />
        </UserDashboardLayout>
      </main>
    </>
  );
}
