import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import NormalLayout from "@/components/layouts/NormalLayout";
import BlogsComponent from "@/components/page/Blogs/Blogs";
import BreadCrumbContainer from "@/components/utils/BreadCrumbContainer";

const inter = Inter({ subsets: ["latin"] });

export default function Blogs() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NormalLayout>
          <BreadCrumbContainer />
          {/* <Header /> */}
          <BlogsComponent />
          {/* <Footer /> */}
        </NormalLayout>
      </main>
    </>
  );
}
