import Head from "next/head";
import styles from "@/styles/properties.module.css";
import { baseUrl, fetchApi } from "../utils/fetchApi";
import PropertiesComponent from "../components/page/Properties";
import NormalLayout from "@/components/layouts/NormalLayout";
import BreadCrumbContainer from "@/components/utils/BreadCrumbContainer";
import { useRouter } from "next/router";

const Properties = ({ properties }) => {
  const router = useRouter();
  const { query } = router;
  return (
    <>
      <Head>
        <title>MyRAJ | Properties</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NormalLayout>
          <BreadCrumbContainer />
          {/* <Header /> */}
          <PropertiesComponent query={query} properties={properties} />
          {/* <Footer /> */}
        </NormalLayout>
      </main>
    </>
  );
};

// export async function getServerSideProps({ query }) {
//   const purpose = query.purpose || "for-rent";
//   const rentFrequency = query.rentFrequency || "yearly";
//   const minPrice = query.minPrice || "0";
//   const maxPrice = query.maxPrice || "1000000";
//   const roomsMin = query.roomsMin || "0";
//   const bathsMin = query.bathsMin || "0";
//   const sort = query.sort || "price-desc";
//   const areaMax = query.areaMax || "35000";
//   const locationExternalIDs = query.locationExternalIDs || "5002";
//   const categoryExternalID = query.categoryExternalID || "4";

//   const data = await fetchApi(
//     `${baseUrl}/properties/list?locationExternalIDs=${locationExternalIDs}&purpose=${purpose}&categoryExternalID=${categoryExternalID}&bathsMin=${bathsMin}&rentFrequency=${rentFrequency}&priceMin=${minPrice}&priceMax=${maxPrice}&roomsMin=${roomsMin}&sort=${sort}&areaMax=${areaMax}`
//   );

//   return {
//     props: {
//       properties: data?.hits,
//     },
//   };
// }

export default Properties;
