import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
// import styles from "@/styles/Home.module.css";
import UserDashboardLayout from "@/components/layouts/UserDashboardLayout";
import UpdateUser from "@/components/page/dashboard/Profile/Update";
import NormalLayout from "@/components/layouts/NormalLayout";
import Section from "@/components/utils/Section";
import Container from "@/components/utils/Container";
import UserDashboardSidebar from "@/components/partials/dashboard/UserDashboardSidebar";
const inter = Inter({ subsets: ["latin"] });

export default function UpdateProfile() {
  return (
    <>
      <Head>
        <title>MyRAJ | Update Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"w-[100vw] overflow-hidden"}>
        <UserDashboardLayout>
          <UpdateUser />
        </UserDashboardLayout>
      </main>
    </>
  );
}
