import Head from "next/head";
import styles from "@/styles/properties.module.css";
import PropertyDetailsComponent from "../../components/page/PropertyDetails";
import NormalLayout from "@/components/layouts/NormalLayout";

// pages/_app.js
import { ChakraProvider } from "@chakra-ui/react";
import { list } from "@/data/Data";
import { useRouter } from "next/router";
import { useDispatch, useSelector } from "react-redux";
import { useEffect, useState } from "react";
import { getPropertyDetail } from "@/store/features/propertySlice";

const PropertyDetails = () => {
  const dispatch = useDispatch();
  const router = useRouter();
  const { id } = router.query;
  useEffect(() => {
    console.log(id);
    dispatch(getPropertyDetail(id));
  }, []);
  const property = useSelector((state) => state.property.detail);
  console.log(property);
  return (
    <>
      <Head>
        <title>Property Detail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChakraProvider>
        <main className={styles.main}>
          <NormalLayout>{property && <PropertyDetailsComponent property={property} />}</NormalLayout>
        </main>
      </ChakraProvider>
    </>
  );
};

export default PropertyDetails;
