import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import NormalLayout from "@/components/layouts/NormalLayout";
import BlogDetailComponent from "@/components/page/Blogs/BlogDetail";
import BreadCrumbContainer from "@/components/utils/BreadCrumbContainer";
import { useRouter } from "next/router";
import { blogs } from "@/data/Data";

const inter = Inter({ subsets: ["latin"] });

export default function BlogDetail() {
  const router = useRouter();
  const { _id } = router.query;
  console.log(_id);
  const blog = blogs.find((item) => _id == item.slug.current);
  console.log(blog);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NormalLayout>
          <BreadCrumbContainer />
          {/* <Header /> */}
          <BlogDetailComponent blog={blog} />
          {/* <Footer /> */}
        </NormalLayout>
      </main>
    </>
  );
}
